name: Manual and Scheduled announcment

on:
  workflow_dispatch:
  schedule:
    - cron: 30 0 * * *
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-python-task:
    runs-on: ubuntu-latest

    steps:
      # Pull the code from your repository
      - name: Checkout Repository
        uses: actions/checkout@v6

      # Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      # Install dependencies from requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Execute the script
      # This passes your GitHub Secret as an environment variable
      - name: Run Python Script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          CRASH_BOY: ${{ secrets.CRASH_BOY }}
          NEWS_API: ${{ secrets.NEWS_API }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TABLE: ${{ secrets.TABLE }}
        run: python src/announcer/main.py
